name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
    - run: yarn install --frozen-lockfile
    - run: yarn npm-run-all build cli:build
    - run: yarn test --coverage
